name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: dropdown
    id: game
    attributes:
      label: Related game (if any)
      options:
        - Manor Lords
        - Minecraft
        - Not game-specific / general app
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What's currently missing or frustrating?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any workarounds you're currently using?
